### ISSUE TITLE
python 2.7.15运行提示不能导入fabric

### ISSUE THREAD

**Issue by pedoc** [zhengyi-yang/ssh-copy-id#3]
conda create -n py27 python=2.7
此环境下
pip install fabric
会安装2.4版本
执行python ssh-copy-id.py 仍然提示无法导入fabric

**Comment by pedoc** [comment]
应该是fabric版本的问题，看官网文档fabric.api应该只在1.x内有，2.x版本已经改进了。我修改了一下，但是会在run命令的时候遇到UnicodeEncodingError的错误，还未解决

**Comment by zhengyi-yang** [comment]
不好意思，这个工具已经多年没有维护了。我会在有时间的时候对依赖的库的版本进行升级。
